# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '0804layout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import matplotlib.image as mpimg
import pandas as pd
import numpy as np
import mplcursors

from PyQt5 import Qt, QtCore, QtGui, QtWidgets, QtWebEngineWidgets

from PyQt5.QtWidgets import QHeaderView
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
from matplotlib.offsetbox import OffsetImage, AnnotationBbox

from rdkit import Chem


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1573, 1015)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName("tabWidget")
        self.RTpredict = QtWidgets.QWidget()
        self.RTpredict.setObjectName("RTpredict")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.RTpredict)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Predictmin = QtWidgets.QLabel(self.RTpredict)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.Predictmin.sizePolicy().hasHeightForWidth())
        self.Predictmin.setSizePolicy(sizePolicy)
        self.Predictmin.setMinimumSize(QtCore.QSize(0, 50))
        self.Predictmin.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Predictmin.setFont(font)
        self.Predictmin.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.Predictmin.setObjectName("Predictmin")
        self.gridLayout_2.addWidget(self.Predictmin, 8, 3, 1, 1)
        self.Applysmi = QtWidgets.QPushButton(self.RTpredict)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Applysmi.sizePolicy().hasHeightForWidth())
        self.Applysmi.setSizePolicy(sizePolicy)
        self.Applysmi.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Applysmi.setFont(font)
        self.Applysmi.setObjectName("Applysmi")
        self.gridLayout_2.addWidget(self.Applysmi, 7, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.RTpredict)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(150, 150))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./SG.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 1)
        self.Drawsketcher = QtWidgets.QLabel(self.RTpredict)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Drawsketcher.setFont(font)
        self.Drawsketcher.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Drawsketcher.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Drawsketcher.setAutoFillBackground(False)
        self.Drawsketcher.setTextFormat(QtCore.Qt.AutoText)
        self.Drawsketcher.setScaledContents(True)
        self.Drawsketcher.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.Drawsketcher.setObjectName("Drawsketcher")
        self.gridLayout_2.addWidget(self.Drawsketcher, 3, 1, 1, 3)
        self.PredictRT = QtWidgets.QLabel(self.RTpredict)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PredictRT.sizePolicy().hasHeightForWidth())
        self.PredictRT.setSizePolicy(sizePolicy)
        self.PredictRT.setMinimumSize(QtCore.QSize(0, 50))
        self.PredictRT.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PredictRT.setFont(font)
        self.PredictRT.setObjectName("PredictRT")
        self.gridLayout_2.addWidget(self.PredictRT, 8, 1, 1, 1)
        self.Showpredict = QtWidgets.QLineEdit(self.RTpredict)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Showpredict.sizePolicy().hasHeightForWidth())
        self.Showpredict.setSizePolicy(sizePolicy)
        self.Showpredict.setMinimumSize(QtCore.QSize(0, 50))
        self.Showpredict.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Showpredict.setFont(font)
        self.Showpredict.setAlignment(QtCore.Qt.AlignCenter)
        self.Showpredict.setReadOnly(True)
        self.Showpredict.setObjectName("Showpredict")
        self.gridLayout_2.addWidget(self.Showpredict, 8, 2, 1, 1)
        self.RTscatter = QtWidgets.QWidget(self.centralwidget)
        self.RTscatter.setAutoFillBackground(False)
        self.RTscatter.setObjectName("RTscatter")

        self.fig1 = plt.Figure()
        self.canvas1 = FigureCanvas(self.fig1)
        self.canvas1_toolbar = NavigationToolbar(self.canvas1, self.RTscatter)
        self.vbox1 = QtWidgets.QVBoxLayout(self.RTscatter)
        self.vbox1.addWidget(self.canvas1_toolbar)
        self.vbox1.addWidget(self.canvas1)

        self.gridLayout_2.addWidget(self.RTscatter, 5, 4, 2, 3)
        self.label_2 = QtWidgets.QLabel(self.RTpredict)
        self.label_2.setMaximumSize(QtCore.QSize(200, 150))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("./KY.jpg"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 6, 1, 1)
        self.Insertsmi = QtWidgets.QLineEdit(self.RTpredict)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Insertsmi.sizePolicy().hasHeightForWidth())
        self.Insertsmi.setSizePolicy(sizePolicy)
        self.Insertsmi.setMinimumSize(QtCore.QSize(0, 50))
        self.Insertsmi.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Insertsmi.setFont(font)
        self.Insertsmi.setAlignment(QtCore.Qt.AlignCenter)
        self.Insertsmi.setObjectName("Insertsmi")
        self.gridLayout_2.addWidget(self.Insertsmi, 7, 2, 1, 1)
        self.Showall = QtWidgets.QPushButton(self.RTpredict)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Showall.sizePolicy().hasHeightForWidth())
        self.Showall.setSizePolicy(sizePolicy)
        self.Showall.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Showall.setFont(font)
        self.Showall.setAutoFillBackground(True)
        self.Showall.setObjectName("Showall")
        self.gridLayout_2.addWidget(self.Showall, 3, 4, 1, 1)
        self.Smi = QtWidgets.QLabel(self.RTpredict)
        self.Smi.setMinimumSize(QtCore.QSize(0, 50))
        self.Smi.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Smi.setFont(font)
        self.Smi.setObjectName("Smi")
        self.gridLayout_2.addWidget(self.Smi, 7, 1, 1, 1)
        self.Outlierdescription = QtWidgets.QLabel(self.RTpredict)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Outlierdescription.setFont(font)
        self.Outlierdescription.setObjectName("Outlierdescription")
        self.gridLayout_2.addWidget(self.Outlierdescription, 8, 4, 1, 3)
        self.Title = QtWidgets.QLabel(self.RTpredict)
        self.Title.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Title.setAutoFillBackground(False)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.gridLayout_2.addWidget(self.Title, 1, 2, 1, 4)
        self.Sketcher = QtWebEngineWidgets.QWebEngineView(self.RTpredict)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sketcher.sizePolicy().hasHeightForWidth())
        self.Sketcher.setSizePolicy(sizePolicy)
        self.Sketcher.setMinimumSize(QtCore.QSize(680, 450))
        self.Sketcher.setMaximumSize(QtCore.QSize(1300, 450))
        self.Sketcher.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Sketcher.setAutoFillBackground(True)
        self.Sketcher.setUrl(QtCore.QUrl("https://pubchem.ncbi.nlm.nih.gov//edit3/index.html"))
        self.Sketcher.setObjectName("Sketcher")
        self.gridLayout_2.addWidget(self.Sketcher, 5, 1, 1, 3)
        self.Outlier = QtWidgets.QLabel(self.RTpredict)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Outlier.setFont(font)
        self.Outlier.setObjectName("Outlier")
        self.gridLayout_2.addWidget(self.Outlier, 7, 4, 1, 2)
        self.Showspecific = QtWidgets.QPushButton(self.RTpredict)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Showspecific.sizePolicy().hasHeightForWidth())
        self.Showspecific.setSizePolicy(sizePolicy)
        self.Showspecific.setMinimumSize(QtCore.QSize(150, 50))
        self.Showspecific.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Showspecific.setFont(font)
        self.Showspecific.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Showspecific.setAutoFillBackground(True)
        self.Showspecific.setObjectName("Showspecific")
        self.gridLayout_2.addWidget(self.Showspecific, 3, 6, 1, 1)
        self.plainTextEdit = QtWidgets.QLineEdit(self.RTpredict)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(500, 50))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_2.addWidget(self.plainTextEdit, 3, 5, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 6, 1, 1, 3)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.RTpredict, "")
        self.RTfit = QtWidgets.QWidget()
        self.RTfit.setObjectName("RTfit")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.RTfit)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.KY_fit = QtWidgets.QLabel(self.RTfit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KY_fit.sizePolicy().hasHeightForWidth())
        self.KY_fit.setSizePolicy(sizePolicy)
        self.KY_fit.setMinimumSize(QtCore.QSize(100, 150))
        self.KY_fit.setMaximumSize(QtCore.QSize(230, 160))
        self.KY_fit.setText("")
        self.KY_fit.setPixmap(QtGui.QPixmap("./KY.jpg"))
        self.KY_fit.setObjectName("KY_fit")
        self.gridLayout_4.addWidget(self.KY_fit, 0, 5, 1, 1)
        self.Title_fit = QtWidgets.QLabel(self.RTfit)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.Title_fit.setFont(font)
        self.Title_fit.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_fit.setObjectName("Title_fit")
        self.gridLayout_4.addWidget(self.Title_fit, 0, 1, 1, 4)
        self.Entermin = QtWidgets.QLabel(self.RTfit)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Entermin.setFont(font)
        self.Entermin.setObjectName("Entermin")
        self.gridLayout_4.addWidget(self.Entermin, 4, 5, 1, 1)
        self.InsertRT = QtWidgets.QLineEdit(self.RTfit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InsertRT.sizePolicy().hasHeightForWidth())
        self.InsertRT.setSizePolicy(sizePolicy)
        self.InsertRT.setMinimumSize(QtCore.QSize(0, 40))
        self.InsertRT.setMaximumSize(QtCore.QSize(400, 60))
        self.InsertRT.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.InsertRT.setFont(font)
        self.InsertRT.setObjectName("InsertRT")
        self.gridLayout_4.addWidget(self.InsertRT, 4, 4, 1, 1)
        self.SG_fit = QtWidgets.QLabel(self.RTfit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SG_fit.sizePolicy().hasHeightForWidth())
        self.SG_fit.setSizePolicy(sizePolicy)
        self.SG_fit.setMinimumSize(QtCore.QSize(150, 150))
        self.SG_fit.setMaximumSize(QtCore.QSize(150, 150))
        self.SG_fit.setText("")
        self.SG_fit.setPixmap(QtGui.QPixmap("./SG.png"))
        self.SG_fit.setScaledContents(True)
        self.SG_fit.setObjectName("SG_fit")
        self.gridLayout_4.addWidget(self.SG_fit, 0, 0, 1, 1)
        self.Calculate = QtWidgets.QPushButton(self.RTfit)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Calculate.setFont(font)
        self.Calculate.setObjectName("Calculate")
        self.gridLayout_4.addWidget(self.Calculate, 5, 4, 1, 1)
        self.FitRT = QtWidgets.QPushButton(self.RTfit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FitRT.sizePolicy().hasHeightForWidth())
        self.FitRT.setSizePolicy(sizePolicy)
        self.FitRT.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.FitRT.setFont(font)
        self.FitRT.setObjectName("FitRT")
        self.gridLayout_4.addWidget(self.FitRT, 4, 2, 1, 1)
        self.FindRT = QtWidgets.QPushButton(self.RTfit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FindRT.sizePolicy().hasHeightForWidth())
        self.FindRT.setSizePolicy(sizePolicy)
        self.FindRT.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.FindRT.setFont(font)
        self.FindRT.setObjectName("FindRT")
        self.gridLayout_4.addWidget(self.FindRT, 4, 0, 1, 1)
        self.Fitfigure = QtWidgets.QWidget(self.RTfit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Fitfigure.sizePolicy().hasHeightForWidth())
        self.Fitfigure.setSizePolicy(sizePolicy)
        self.Fitfigure.setMaximumSize(QtCore.QSize(850, 580))
        self.Fitfigure.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Fitfigure.setAutoFillBackground(False)

        self.fig2 = plt.Figure()
        self.canvas2 = FigureCanvas(self.fig2)
        self.canvas2_toolbar = NavigationToolbar(self.canvas2, self.Fitfigure)
        self.vbox2 = QtWidgets.QVBoxLayout(self.Fitfigure)
        self.vbox2.addWidget(self.canvas2_toolbar)
        self.vbox2.addWidget(self.canvas2)

        self.Fitfigure.setObjectName("Fitfigure")
        self.gridLayout_4.addWidget(self.Fitfigure, 1, 3, 1, 3)
        self.Fittable = QtWidgets.QTableWidget(self.RTfit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Fittable.sizePolicy().hasHeightForWidth())
        self.Fittable.setSizePolicy(sizePolicy)
        self.Fittable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Fittable.setFont(font)
        self.Fittable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Fittable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Fittable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Fittable.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.Fittable.setRowCount(6)
        self.Fittable.setColumnCount(3)
        self.Fittable.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)  # 셀 수정 가능하게 변경
        self.Fittable.setHorizontalHeaderLabels(["Metabolite", "Your experimental RT", "Predicted RT"])
        self.Fittable.resizeColumnsToContents()
        self.Fittable.resizeRowToContents(6)
        # self.Fittable.horizontalHeader().setStretchLastSection(True)
        self.Fittable.setObjectName("Fittable")
        self.Fittable.horizontalHeader().setCascadingSectionResizes(False)
        self.Fittable.horizontalHeader().setDefaultSectionSize(220)
        self.Fittable.horizontalHeader().setHighlightSections(False)
        self.Fittable.verticalHeader().setCascadingSectionResizes(False)
        self.Fittable.verticalHeader().setDefaultSectionSize(90)
        self.Fittable.verticalHeader().setSortIndicatorShown(False)
        self.Fittable.verticalHeader().setStretchLastSection(False)
        self.gridLayout_4.addWidget(self.Fittable, 1, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 2, 0, 1, 6)
        self.Fitmin = QtWidgets.QLabel(self.RTfit)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Fitmin.setFont(font)
        self.Fitmin.setObjectName("Fitmin")
        self.gridLayout_4.addWidget(self.Fitmin, 7, 5, 1, 1)
        self.Fitresult = QtWidgets.QLineEdit(self.RTfit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Fitresult.sizePolicy().hasHeightForWidth())
        self.Fitresult.setSizePolicy(sizePolicy)
        self.Fitresult.setMinimumSize(QtCore.QSize(0, 40))
        self.Fitresult.setMaximumSize(QtCore.QSize(400, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Fitresult.setFont(font)
        self.Fitresult.setObjectName("Fitresult")
        self.Fitresult.setAlignment(QtCore.Qt.AlignCenter)
        self.Fitresult.setReadOnly(True)
        self.gridLayout_4.addWidget(self.Fitresult, 7, 4, 1, 1)
        self.EnterRT = QtWidgets.QLabel(self.RTfit)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.EnterRT.setFont(font)
        self.EnterRT.setAlignment(QtCore.Qt.AlignCenter)
        self.EnterRT.setObjectName("EnterRT")
        self.gridLayout_4.addWidget(self.EnterRT, 4, 3, 1, 1)
        self.FittedRT = QtWidgets.QLabel(self.RTfit)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.FittedRT.setFont(font)
        self.FittedRT.setAlignment(QtCore.Qt.AlignCenter)
        self.FittedRT.setObjectName("FittedRT")
        self.gridLayout_4.addWidget(self.FittedRT, 7, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.tabWidget.addTab(self.RTfit, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1573, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(
            _translate("MainWindow", "AI Predictor of LC Retention Time for Dansylated Metabolites"))
        self.Predictmin.setText(_translate("MainWindow", "min"))
        self.Applysmi.setText(_translate("MainWindow", "Apply SMILES\n"
                                                       " to predict retention time"))
        self.Drawsketcher.setText(_translate("MainWindow",
                                             "<html><head/><body><p><span style=\" font-size:14pt;\">Draw a structure in the sketcher below</span></p></body></html>"))
        self.PredictRT.setText(_translate("MainWindow", "Predicted retention time:"))
        self.Showall.setText(_translate("MainWindow", "Show all metabolites"))
        self.Smi.setText(_translate("MainWindow", "SMILES:"))
        self.Outlierdescription.setText(_translate("MainWindow", "There are outliers in scatter above.\n"
                                                                 "Outliers are these:\n"
                                                                 "3-methyl-histidine, L-Histidinol, 1-Methylhistidine, L-Histidine, Histidinyl-Alanine, Hippuric acid,\n"
                                                                 "Alanyl-Histidine, 3-Hydroxyanthranilic acid, Xanthurenic acid, Oxidized glutathione,\n"
                                                                 "2-aminooctanoic acid, Cadaverine, Caffeic acid, Iodotyrosine, and Naringenin."))
        self.Title.setText(_translate("MainWindow", "AI Predictor of LC Retention Time for \n"
                                                    "Dansylated Metabolites"))
        self.Outlier.setText(_translate("MainWindow", "About outlier:"))
        self.Showspecific.setText(_translate("MainWindow", "Show specific metabolites"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RTpredict),
                                  _translate("MainWindow", "Retention time predict"))
        self.Title_fit.setText(_translate("MainWindow", "AI Predictor of LC Retention Time for \n"
                                                        "Dansylated Metabolites"))
        self.Entermin.setText(_translate("MainWindow", "min"))
        self.Calculate.setText(_translate("MainWindow", "Calculate!"))
        self.FitRT.setText(_translate("MainWindow", "Fit retention time"))
        self.FindRT.setText(_translate("MainWindow", "Find predicted retention time"))
        self.Fitmin.setText(_translate("MainWindow", "min"))
        self.EnterRT.setText(_translate("MainWindow", "Enter Your retention time"))
        self.FittedRT.setText(_translate("MainWindow", "Fitted retention time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RTfit), _translate("MainWindow", "Retention time fit"))


from PyQt5 import QtWebEngineWidgets

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
